const availableActions = [
  "metrics.menu",
  "metrics.list",
  "metrics.export",

  "entries.menu",
  "entries.list",
  "entries.create",
  "entries.edit",
  "entries.delete",

  "exits.menu",
  "exits.list",
  "exits.list-own",
  "exits.create",
  "exits.edit",
  "exits.edit-own",
  "exits.delete-own",
  "exits.validate",
  "exits.delete",

  "catalog.menu",
  "catalog.list",
  "catalog.list-private",
  "catalog.see-audience",
  "catalog.cart",

  "offcuts.menu",
  "offcuts.list",
  "offcuts.list-private",
  "offcuts.create",
  "offcuts.edit",
  "offcuts.delete",

  "transports.menu",
  "transports.list",
  "transports.create",
  "transports.edit",
  "transports.delete",

  "investments.menu",
  "investments.list",
  "investments.create",
  "investments.edit",
  "investments.delete",

  "users.menu",
  "users.list",
  "users.create",
  "users.edit",
  "users.delete",

  "roles.menu",
  "roles.list",
  "roles.create",
  "roles.edit",
  "roles.delete",

  "mails.menu",
  "mails.list",
  "mails.create",
  "mails.edit",
  "mails.delete",

  "matters.menu",
  "matters.list",
  "matters.create",
  "matters.edit",
  "matters.delete",

  "materials.menu",
  "materials.list",
  "materials.create",
  "materials.edit",
  "materials.delete",

  "sizes.menu",
  "sizes.list",
  "sizes.create",
  "sizes.edit",
  "sizes.delete",

  "colors.menu",
  "colors.list",
  "colors.create",
  "colors.edit",
  "colors.delete",

  "qualities.menu",
  "qualities.list",
  "qualities.create",
  "qualities.edit",
  "qualities.delete",

  "audiences.menu",
  "audiences.list",
  "audiences.create",
  "audiences.edit",
  "audiences.delete",

  "brandPolicies.menu",
  "brandPolicies.list",
  "brandPolicies.create",
  "brandPolicies.edit",
  "brandPolicies.delete",

  "transportModes.menu",
  "transportModes.list",
  "transportModes.create",
  "transportModes.edit",
  "transportModes.delete",

  "transportReasons.menu",
  "transportReasons.list",
  "transportReasons.create",
  "transportReasons.edit",
  "transportReasons.delete",

  "investmentTypes.menu",
  "investmentTypes.list",
  "investmentTypes.create",
  "investmentTypes.edit",
  "investmentTypes.delete",

  "investmentConditions.menu",
  "investmentConditions.list",
  "investmentConditions.create",
  "investmentConditions.edit",
  "investmentConditions.delete",
];

export default availableActions;
