name: Publish
on: 
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install yarn
        run: npm install -g yarn
      - name: Logging into docker registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin registry.bleumatin.fr
      - name: Building
        run: yarn build-image
      - name: Deploying
        run: yarn deploy
      - name: Restarting
        run: curl -X POST https://portainer.bleumatin.fr/api/stacks/webhooks/f62a369c-9302-45df-94d3-de246732df80
